version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: build/Dockerfile   # <-- ważne: wskazujemy Dockerfile w katalogu build/
    ports:
      - "5000:5000"                  # host:container (poprzednio było 5000:500 - literówka)
    environment:
      - FLASK_APP=app
      - FLASK_RUN_PORT=5000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 3s
      retries: 10
